# https://ci.appveyor.com/project/spyder-ide/spyder-kernels

environment:

  global:
    PYTHON: "C:\\Miniconda36-x64"

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.6"
    - PYTHON_VERSION: "3.7"

platform:
  -x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "conda create -y -n test python=%PYTHON_VERSION%"
  - "activate test"
  - "conda install -q -y --file requirements/windows.txt"
  - "conda install -q -y --file requirements/tests.txt"
  - "pip install -e ."

build: false

test_script:
  - "pytest -x -vv spyder_kernels"