channels:
- defaults
dependencies:
- cloudpickle
- ipykernel
- wurlitzer >=1.0.3  # [unix]
# Pin pip version since we are getting 9.x and it causes IPython 6.1.0 to be installed
- pip >=19.3.1
- click =7  # [py27]
# For testing
- codecov
- cython
- dask
- flaky
- matplotlib
- nomkl  # [unix]
- mock
- numpy
- pandas
- pytest
- pytest-cov
- scipy
- xarray
- pillow
